#Usa una imagen base de Python
FROM python:3.8
#Establece el directorio de trabajo dentro del contenedor 
WORKDIR /app
#Copia el archvo de la aplicacion al contenedor
COPY app.py .
#Comando para ejecitar la aplicacion
CMD ["python", "app.py"]

